name: Build
on: [push]
jobs:
  main:
    runs-on: macos-latest
    steps:
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "10.0"
      - name: Build
        run: ./build-native-lib.sh && dotnet build -c Release